"""Add new models and call session fields

Revision ID: 4eb65017697a
Revises: 002_add_operating_hours
Create Date: 2026-02-14 11:13:35.631855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Import pgvector for vector column type
try:
    import pgvector
    from pgvector.sqlalchemy import Vector
except ImportError:
    # Fallback if pgvector not available - will use regular JSON
    Vector = None
    pgvector = None

# revision identifiers, used by Alembic.
revision = '4eb65017697a'
down_revision = '002_add_operating_hours'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_integrations_id'), 'calendar_integrations', ['id'], unique=False)
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_id'), 'knowledge_base_documents', ['id'], unique=False)
    op.create_table('sms_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_templates_id'), 'sms_templates', ['id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),  # Using JSON instead of vector
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_base_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.drop_table('call_logs')
    op.create_index(op.f('ix_ai_training_scenarios_id'), 'ai_training_scenarios', ['id'], unique=False)
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('appointments', 'customer_phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('appointments', 'service_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'confirmed'::character varying"))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('businesses', sa.Column('operating_hours', sa.JSON(), nullable=True))
    op.alter_column('businesses', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_businesses_user_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.add_column('call_sessions', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('call_sessions', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('call_sessions', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('call_sessions', sa.Column('recording_url', sa.Text(), nullable=True))
    op.add_column('call_sessions', sa.Column('recording_duration', sa.Integer(), nullable=True))
    op.add_column('call_sessions', sa.Column('voicemail_detected', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_call_sessions_business_id'), table_name='call_sessions')
    op.drop_index(op.f('idx_call_sessions_started_at'), table_name='call_sessions')
    op.alter_column('conversation_messages', 'entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_conversation_messages_call_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('idx_conversation_messages_timestamp'), table_name='conversation_messages')
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.alter_column('integrations', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('integrations', 'credentials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_integrations_business_id'), table_name='integrations')
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.alter_column('system_logs', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('idx_system_logs_level'), table_name='system_logs')
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.create_index(op.f('idx_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('idx_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.alter_column('system_logs', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.create_index(op.f('idx_integrations_business_id'), 'integrations', ['business_id'], unique=False)
    op.alter_column('integrations', 'credentials',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('integrations', 'configuration',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.create_index(op.f('idx_conversation_messages_timestamp'), 'conversation_messages', ['timestamp'], unique=False)
    op.create_index(op.f('idx_conversation_messages_call_session_id'), 'conversation_messages', ['call_session_id'], unique=False)
    op.alter_column('conversation_messages', 'entities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_call_sessions_started_at'), 'call_sessions', ['started_at'], unique=False)
    op.create_index(op.f('idx_call_sessions_business_id'), 'call_sessions', ['business_id'], unique=False)
    op.drop_column('call_sessions', 'voicemail_detected')
    op.drop_column('call_sessions', 'recording_duration')
    op.drop_column('call_sessions', 'recording_url')
    op.drop_column('call_sessions', 'language')
    op.drop_column('call_sessions', 'sentiment')
    op.drop_column('call_sessions', 'customer_name')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.create_index(op.f('idx_businesses_user_id'), 'businesses', ['user_id'], unique=False)
    op.alter_column('businesses', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('businesses', 'operating_hours')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.alter_column('appointments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'confirmed'::character varying"))
    op.alter_column('appointments', 'service_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'customer_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('appointments', 'updated_at')
    op.drop_index(op.f('ix_ai_training_scenarios_id'), table_name='ai_training_scenarios')
    op.create_table('call_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('call_sid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('call_logs_business_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('call_logs_pkey'))
    )
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_sms_templates_id'), table_name='sms_templates')
    op.drop_table('sms_templates')
    op.drop_index(op.f('ix_knowledge_base_documents_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_index(op.f('ix_calendar_integrations_id'), table_name='calendar_integrations')
    op.drop_table('calendar_integrations')
    # ### end Alembic commands ###