"""Add source to Appointment model

Revision ID: e9d4f30ed2e5
Revises: 20260220_team_recording
Create Date: 2026-02-20 14:13:35.230608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9d4f30ed2e5'
down_revision = '20260220_team_recording'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'source')
    # ### end Alembic commands ###