"""add_inventory_to_menu_items

Revision ID: a35c6c409afb
Revises: e9d4f30ed2e5
Create Date: 2026-02-21 17:30:40.976926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a35c6c409afb'
down_revision = 'e9d4f30ed2e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_count', sa.Integer(), nullable=True),
    sa.Column('avg_success_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('scenario_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_snapshots_id'), 'training_snapshots', ['id'], unique=False)
    op.create_table('benchmark_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('total_scenarios', sa.Integer(), nullable=True),
    sa.Column('passed_scenarios', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('detailed_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['training_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_results_id'), 'benchmark_results', ['id'], unique=False)
    op.execute("UPDATE appointments SET source = 'internal' WHERE source IS NULL")
    op.alter_column('appointments', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('business_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('business_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('business_templates', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(op.f('business_templates_template_key_key'), 'business_templates', type_='unique')
    op.alter_column('business_type_suggestions', 'confidence_weight',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('business_type_suggestions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_call_recordings_business_id'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_call_session_id'), table_name='call_recordings')
    op.create_index(op.f('ix_call_recordings_id'), 'call_recordings', ['id'], unique=False)
    op.alter_column('customers', 'communication_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('customers', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.alter_column('intent_classifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('menu_items', sa.Column('inventory', sa.Integer(), nullable=True))
    op.drop_column('orders', 'accounting_invoice_id')
    op.drop_column('orders', 'quickbooks_invoice_id')
    op.alter_column('team_members', 'weekly_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_team_members_business_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.alter_column('template_versions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template_versions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_members_business_id'), 'team_members', ['business_id'], unique=False)
    op.alter_column('team_members', 'weekly_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('orders', sa.Column('quickbooks_invoice_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('accounting_invoice_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('menu_items', 'inventory')
    op.alter_column('intent_classifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.alter_column('customers', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('customers', 'communication_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_call_recordings_id'), table_name='call_recordings')
    op.create_index(op.f('ix_call_recordings_call_session_id'), 'call_recordings', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_business_id'), 'call_recordings', ['business_id'], unique=False)
    op.alter_column('business_type_suggestions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('business_type_suggestions', 'confidence_weight',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.create_unique_constraint(op.f('business_templates_template_key_key'), 'business_templates', ['template_key'])
    op.alter_column('business_templates', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('business_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('business_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('appointments', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_benchmark_results_id'), table_name='benchmark_results')
    op.drop_table('benchmark_results')
    op.drop_index(op.f('ix_training_snapshots_id'), table_name='training_snapshots')
    op.drop_table('training_snapshots')
    # ### end Alembic commands ###