"""add_delivery_method_to_orders

Revision ID: d88db6c8283c
Revises: a35c6c409afb
Create Date: 2026-02-21 18:07:06.161827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88db6c8283c'
down_revision = 'a35c6c409afb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'delivery_method')
    # ### end Alembic commands ###